exclude: '^docs/|/migrations/|devcontainer.json'
default_stages: [pre-commit]

default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key

  - repo: https://github.com/adamchainz/django-upgrade
    rev: '1.22.1'
    hooks:
      - id: django-upgrade
        args: ['--target-version', '5.0']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.35.3
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-commit-message
        stages: [commit-msg]
        args: ['--pattern', '^(feat|fix|docs|style|refactor|test|chore)(\\([a-z0-9\\-]+\\))?: .+']

  - repo: https://github.com/jeris90/branch-name-linter
    rev: v1.0.0
    hooks:
      - id: branch-name-linter
        stages: [push]
        args: ['--pattern', '^(feature|bugfix|hotfix|refactor|chore|docs)/[a-z0-9\\-_]+$']

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
