# Generated by Django 5.1.5 on 2025-07-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_profile_set',
            field=models.BooleanField(default=False),
        ),
    ]
